Algoritmo "circulo"
//Fazer um programa pra ler o valor de R do raio de um circulo
//e depois mostrar o valor da área do circulo
//a formula da área do circulo é: área = pi.r2
Var

 raio, area : real

Inicio
//Estrutura inicial para obter valor do raio do circulo
      escreva("Digite o valor do raio do circulo: ")
      leia(raio)
      escreval

//Estrutura para calcular e mostrar o valor da área
      area <- pi*exp(raio, 2)
      escreva("Área = ", area:5:3)

Fimalgoritmo