Algoritmo "teste saida"

Var
  a:inteiro
  b:real
  c:caractere
  d:logico

Inicio
      a<-32
      b<-2.34567
      c<-"Bom dia"
      d<-VERDADEIRO
      // o comando "<-" atribui valores as variaveis declaradas
      
      
      escreval(a)
      //os dois pontos após a declaração da variavel formata os valores mostrados
      escreval(b:2:2)
      escreval(c)
      escreval(d)
      


Fimalgoritmo