Algoritmo "soma"
//Criar um algoritmo que leia dois valores inteiros
//e mostre na tela o valor da soma entre eles

Var

   valor1, valor2, soma : inteiro

Inicio

//Estrutura para ler os valores
    Escreva("Digite o primeiro valor: ")
    Leia(valor1)
    Escreva("Digite o segundo valor: ")
    Leia(valor2)
    Escreval
    
//Estrutura para calcular e mostrar a soma dos valores
    soma <- valor1 + valor2
    Escreva("A soma dos dois valores é:",soma)


Fimalgoritmo